name: workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  placeholder:
    runs-on: ubuntu-latest
    environment: pipy
    steps:
      - uses: actions/checkout@v4
      - name: Placeholder
        run: echo "markmaton repository initialized"
